import type { Metadata } from "next";
import "../styles/App.scss";
import { Header } from "@/components/Header/Header";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
    title: "My Horoscope",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="wrapper">
                <Providers>
                    <Header />
                    <main className="main">{children}</main>
                    <footer></footer>
                </Providers>
            </body>
        </html>
    );
}
